## Importing Libraries

In [1]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.preprocessing import TransactionEncoder

## Generate Dataframe

In [2]:
with open("Data/store_data.csv",'r') as f:
    dataset = [ [x.strip() for x in line.split(',')] for line in [ x.strip() for x in f.readlines() ]]

te = TransactionEncoder()
te_try = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_try, columns=te.columns_)
df.head()

,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,body spray,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,True,True,False,True,False,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [3]:
MIN_SUPP = 0.05

## Apriori algorithms for frequent pattern mining

In [4]:
apriori(df,min_support=MIN_SUPP)

     support  itemsets
0   0.087188      (14)
1   0.081056      (16)
2   0.059992      (22)
3   0.163845      (24)
4   0.080389      (29)
5   0.051060      (30)
6   0.179709      (36)
7   0.079323      (39)
8   0.170911      (42)
9   0.063325      (47)
10  0.095321      (48)
11  0.052393      (50)
12  0.132116      (53)
13  0.098254      (54)
14  0.076523      (64)
15  0.129583      (70)
16  0.238368      (71)
17  0.065858      (80)
18  0.095054      (81)
19  0.071457      (96)
20  0.050527      (98)
21  0.174110      (99)
22  0.068391     (107)
23  0.062525     (109)
24  0.058526     (115)
25  0.052660  (24, 71)
26  0.050927  (36, 71)
27  0.059725  (99, 71)

## Model Training with Column Result return

In [5]:
apriori(df,min_support=MIN_SUPP, use_colnames=True)

     support                    itemsets
0   0.087188                   (burgers)
1   0.081056                      (cake)
2   0.059992                   (chicken)
3   0.163845                 (chocolate)
4   0.080389                   (cookies)
5   0.051060               (cooking oil)
6   0.179709                      (eggs)
7   0.079323                  (escalope)
8   0.170911              (french fries)
9   0.063325           (frozen smoothie)
10  0.095321         (frozen vegetables)
11  0.052393             (grated cheese)
12  0.132116                 (green tea)
13  0.098254               (ground beef)
14  0.076523            (low fat yogurt)
15  0.129583                      (milk)
16  0.238368             (mineral water)
17  0.065858                 (olive oil)
18  0.095054                  (pancakes)
19  0.071457                    (shrimp)
20  0.050527                      (soup)
21  0.174110                 (spaghetti)
22  0.068391                  (tomatoes)
23  0.062525                    (turkey)
24  0.058526          (whole wheat rice)
25  0.052660  (chocolate, mineral water)
26  0.050927       (eggs, mineral water)
27  0.059725  (spaghetti, mineral water)

## Calculate the length of Itemset

In [6]:
frequent_itemsets = apriori(df, min_support=MIN_SUPP, use_colnames=True)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets

     support                    itemsets  length
0   0.087188                   (burgers)       1
1   0.081056                      (cake)       1
2   0.059992                   (chicken)       1
3   0.163845                 (chocolate)       1
4   0.080389                   (cookies)       1
5   0.051060               (cooking oil)       1
6   0.179709                      (eggs)       1
7   0.079323                  (escalope)       1
8   0.170911              (french fries)       1
9   0.063325           (frozen smoothie)       1
10  0.095321         (frozen vegetables)       1
11  0.052393             (grated cheese)       1
12  0.132116                 (green tea)       1
13  0.098254               (ground beef)       1
14  0.076523            (low fat yogurt)       1
15  0.129583                      (milk)       1
16  0.238368             (mineral water)       1
17  0.065858                 (olive oil)       1
18  0.095054                  (pancakes)       1
19  0.071457                    (shrimp)       1
20  0.050527                      (soup)       1
21  0.174110                 (spaghetti)       1
22  0.068391                  (tomatoes)       1
23  0.062525                    (turkey)       1
24  0.058526          (whole wheat rice)       1
25  0.052660  (chocolate, mineral water)       2
26  0.050927       (eggs, mineral water)       2
27  0.059725  (spaghetti, mineral water)       2

## Length is 2 and Support is > MIN_SUPP

In [7]:
frequent_itemsets[ (frequent_itemsets['length'] == 2) & (frequent_itemsets['support'] >= MIN_SUPP) ]

     support                    itemsets  length
25  0.052660  (chocolate, mineral water)       2
26  0.050927       (eggs, mineral water)       2
27  0.059725  (spaghetti, mineral water)       2

## Conclusion
From analysis of the transaction data we can conclude that mineral water is purchased with chocolate,eggs,spaghetti.